export const BASKETBALL_COPY = {
 'Warehouse':['仓库','Almacén'],
 'Playable basketball court. Tap to move the ball handler, or use arrows or W A S D. Hold and release the shoot button or Space to shoot. E passes or steals; Q returns to Shuyu.':['可玩的篮球场。点按球场引导持球人移动，或使用方向键、W A S D。按住投篮按钮或空格并松开投篮。E 传球或抢断，Q 切回 Shuyu。','Cancha jugable. Toca para mover al jugador con balón o usa las flechas o W A S D. Mantén y suelta el botón de tiro o Espacio para tirar. E pasa o roba; Q vuelve a Shuyu.'],
 'Tap the court to move. Hold the shoot button, then release in green. E: pass or steal. Q: back to Shuyu. Arrow keys / WASD also move.':['点按球场移动。按住投篮按钮，在绿色区域松开。E：传球或抢断。Q：切回 Shuyu。也可以用方向键或 WASD 移动。','Toca la cancha para moverte. Mantén el botón de tiro y suelta en verde. E: pasar o robar. Q: volver a Shuyu. También puedes moverte con las flechas o WASD.'],
 'Use Pass to find a teammate. The gold ring marks who you control; a star marks Shuyu’s pass recipient. Attack the right basket.':['点击传球寻找队友。金色圈表示你控制的球员；星标表示接到 Shuyu 直接传球的队友。进攻右侧篮筐。','Usa Pasar para encontrar a un compañero. El aro dorado marca a quién controlas; una estrella marca al receptor del pase de Shuyu. Ataca el aro derecho.'],
  'Basketball scoreboard': ['篮球计分板', 'Marcador de baloncesto'],
  'Playable basketball court': ['可玩的篮球场', 'Cancha de baloncesto interactiva'],
 'Life outside work':['工作之外的生活','Mi vida fuera del trabajo'],
 'Step outside':['走到室外','Salir al exterior'],
 'Exit to the basketball court':['走出仓库，前往篮球场','Salir a la cancha de baloncesto'],
 'Walking to the exit. Time for a little basketball.':['正在走向出口。来打会儿篮球吧。','Caminando a la salida. Hora de jugar al baloncesto.'],
 'Step outside for basketball':['走出仓库打篮球','Salir a jugar al baloncesto'],
 'OFF THE CLOCK':['下班时间','FUERA DEL TRABAJO'],
 'Same Shuyu. Different court.':['同一个 Shuyu，不一样的主场。','El mismo Shuyu. Otra cancha.'],
 'Outside operations, I’m a basketball fan. Welcome to my slightly biased pickup game.':['工作之外，我是个篮球迷。欢迎来玩这场有点偏心的野球赛。','Fuera de las operaciones, soy aficionado al baloncesto. Bienvenido a mi partido con reglas un poco a mi favor.'],
 'Back to the warehouse':['返回仓库','Volver al almacén'],
 'SHUYU’S HOUSE RULE':['SHUYU 的主场规则','LA REGLA DE SHUYU'],
 'Only Shuyu or a teammate receiving his direct pass can score. Everyone else is here for the cardio.':['只有 Shuyu 或直接接到他传球的队友能得分。其他人就当练体能啦。','Solo Shuyu o un compañero que reciba su pase directo pueden anotar. Los demás han venido a hacer cardio.'],
 'Squad points':['球队得分','Puntos del equipo'],
 'Shuyu’s points':['Shuyu 得分','Puntos de Shuyu'],
 'Shuyu’s assists':['Shuyu 助攻','Asistencias de Shuyu'],
 'Shot clock':['进攻时间','Reloj de posesión'],
 'First to 21 · Full court · 5 on 5':['先得21分 · 全场 · 5对5','A 21 puntos · Cancha completa · 5 contra 5'],
 'Playable basketball court. Use arrows or W A S D to move. Hold and release Space or the shoot button to shoot. E passes or steals; Q returns to Shuyu.':['可玩的篮球场。方向键或 W A S D 移动。按住并松开空格或投篮按钮进行投篮。E 传球或抢断；Q 切回 Shuyu。','Cancha jugable. Usa las flechas o W A S D para moverte. Mantén y suelta Espacio o el botón de tiro para lanzar. E pasa o roba; Q vuelve a Shuyu.'],
 'Grab a ball. Join the run.':['拿起球，上场吧。','Coge el balón. Entra al partido.'],
 'Move into range, hold for about one second, then release in green. Pass to a teammate for a Shuyu assist.':['进入射程，按住约一秒，在绿色区域松开。传给队友，送出一次 Shuyu 助攻。','Acércate al aro, mantén pulsado un segundo y suelta en verde. Pasa a un compañero para sumar una asistencia de Shuyu.'],
 'Start pickup':['开始比赛','Empezar partido'],
 'Loading the court…':['正在准备球场…','Cargando la cancha…'],
 'The court artwork could not load. Try reloading this page.':['球场画面加载失败，请重新加载页面。','No se pudo cargar la cancha. Prueba a recargar la página.'],
 'Resume game':['继续比赛','Reanudar partido'],
 'Game paused':['比赛暂停','Partido en pausa'],
 'Play again':['再来一场','Jugar de nuevo'],
 '21! A little teamwork. A lot of Shuyu.':['21分！一点团队合作，加上很多 Shuyu。','¡21! Un poco de trabajo en equipo. Mucho Shuyu.'],
 'Move':['移动','Moverse'],
 'Hold to shoot':['按住投篮','Mantén para tirar'],
 'Pass / steal':['传球 / 抢断','Pasar / robar'],
 'Back to Shuyu':['切回 Shuyu','Volver a Shuyu'],
 'Pause':['暂停','Pausa'],
 'Restart':['重新开始','Reiniciar'],
 'Move up':['向上移动','Mover arriba'],
 'Move down':['向下移动','Mover abajo'],
 'Move left':['向左移动','Mover a la izquierda'],
 'Move right':['向右移动','Mover a la derecha'],
 'Shot timing':['投篮时机','Tiempo del tiro'],
 'Release in green · about 1 second':['在绿色区域松开 · 约1秒','Suelta en verde · cerca de 1 segundo'],
 'Arrow keys / WASD: move. Space or hold the court: shoot. E: pass or steal. Q: back to Shuyu.':['方向键 / WASD：移动。空格或按住球场：投篮。E：传球或抢断。Q：切回 Shuyu。','Flechas / WASD: moverse. Espacio o mantener la cancha: tirar. E: pasar o robar. Q: volver a Shuyu.'],
 'Tap a mint teammate to pass. The gold ring marks who you control; a star marks Shuyu’s pass recipient. Attack the right basket.':['点按薄荷绿队友传球。金色圈表示你控制的球员；星标表示直接接到 Shuyu 传球的队友。进攻右侧篮筐。','Toca a un compañero verde para pasar. El aro dorado indica a quién controlas; una estrella marca al receptor del pase de Shuyu. Ataca el aro derecho.'],
 'Ready for a little pickup?':['准备好来一场了吗？','¿Listo para un partido?'],
 'Find your spot. Hold, then release.':['找到位置，按住，再松开。','Busca tu sitio. Mantén y suelta.'],
 'Get the ball first. Press E to steal when close.':['先拿到球。靠近持球人后按 E 抢断。','Primero consigue el balón. Pulsa E para robar cuando estés cerca.'],
 'No Shuyu, no bucket. House rules.':['没有 Shuyu，就不算进球。这是主场规则。','Sin Shuyu no hay canasta. Reglas de la casa.'],
 'Green release!':['绿色出手！','¡Tiro en verde!'],
 'Early release. Aim for green.':['出手早了，对准绿色区。','Soltaste pronto. Busca el verde.'],
 'Late release. Aim for green.':['出手晚了，对准绿色区。','Soltaste tarde. Busca el verde.'],
 'Shuyu’s pass. Your teammate can score.':['Shuyu 的传球，队友现在可以得分。','Pase de Shuyu. Tu compañero puede anotar.'],
 'Back to Shuyu.':['球回到 Shuyu。','De vuelta a Shuyu.'],
 'Pass received. Get Shuyu involved to score.':['接到传球了，让 Shuyu 参与才能得分。','Pase recibido. Involucra a Shuyu para anotar.'],
 'You’re controlling Shuyu.':['现在由你控制 Shuyu。','Ahora controlas a Shuyu.'],
 'Stolen! Turn defense into a bucket.':['抢断成功！把防守变成得分。','¡Robo! Convierte la defensa en una canasta.'],
 'Get closer to the ball handler to steal.':['靠近持球人再抢断。','Acércate al jugador con balón para robar.'],
 'Shuyu has the ball. Attack the right basket.':['Shuyu 持球，进攻右侧篮筐。','Shuyu tiene el balón. Ataca el aro derecho.'],
 'They have the ball. Chase it down and press E to steal.':['对手持球，追上去按 E 抢断。','Tienen el balón. Acércate y pulsa E para robar.'],
 'Shuyu for three!':['Shuyu 三分命中！','¡Triple de Shuyu!'],
 'Shuyu gets the bucket!':['Shuyu 得分！','¡Canasta de Shuyu!'],
 'Bucket! That’s a Shuyu assist.':['进球！Shuyu 记一次助攻。','¡Canasta! Asistencia de Shuyu.'],
 'Their shot doesn’t count. This is Shuyu’s court.':['对手进球不算，这可是 Shuyu 的球场。','Su tiro no cuenta. Esta es la cancha de Shuyu.'],
 'Off the rim. Get back on defense.':['弹框而出，快回防。','Rebota en el aro. Vuelve a defender.'],
 'No Shuyu pass, no points. Get him the ball.':['没有 Shuyu 的传球就不得分，把球给他。','Sin pase de Shuyu no hay puntos. Dale el balón.'],
 'Shot clock. Change of possession.':['进攻超时，交换球权。','Tiempo de posesión agotado. Cambio de balón.'],
 'Turnover. Win it back!':['失误了，快把球抢回来！','Pérdida de balón. ¡Recupéralo!'],
 'Shuyu can score':['Shuyu 可以得分','Shuyu puede anotar'],
 'Assist unlocked':['助攻已解锁','Asistencia habilitada'],
 'Needs Shuyu’s pass':['需要 Shuyu 的传球','Necesita un pase de Shuyu'],
 'Get back on defense':['快回防','Vuelve a defender'],
 'Ball in flight':['球在空中','Balón en el aire'],
};
