import { AI_PROJECT } from './ai-operations.mjs';
import { BIN_LINERS, A_LEVEL_BEAMS } from './safety-projects.mjs';
export const PROJECTS = {
  liners: BIN_LINERS,
  stowguidance: {
    number: '02', title: 'Stow Guidance Tool Improvement Project', place: 'STOW SATELLITE DROP ZONE', color: 'var(--amber)',
    summary: 'Remove the scan-and-wait step.',
    lead: 'I moved cage scanning into the route stowers already travel, so aisle recommendations are ready before the cage is mounted.',
    tags: ['Physical workflow design', 'Automatic barcode scanning', 'Adopted by another building'],
    content: `<button class="outline-button" type="button" data-replay-stowguidance>Replay the before-and-after sequence ↗</button><div class="impact-facts" aria-label="Stow Guidance impact"><div><strong>≈60 sec</strong><span>Recovered per cage changeover</span></div><div><strong>1 labor-hour</strong><span>Recovered per team operating hour</span></div><div><strong>2+ buildings</strong><span>Design adopted, as reported</span></div></div>
      <section class="story-section"><h3>Before the change</h3><p>Stowers mounted a cage on their order picker, then used a Kindle tablet to scan its barcode and wait for the stow guidance system to return the recommended aisles or zones. The tablet camera was difficult to scan with, and the system responded slowly on the device.</p><p>Even when the scan worked on the first attempt, that process took about one minute per cage changeover. Retries could add more time.</p></section>
      <section class="story-section"><h3>What I designed</h3><p>I designed the “car wash” arrangement with three parallel lanes and a doorway-shaped strut frame over each lane. The frames are bolted to the floor and powered from the warehouse ceiling, placing the scanners directly in the route cages take out of the work-in-progress queue.</p><p>A fixed Zebra scanner reads the cage barcode automatically. A TV mounted on the overhead strut displays the system’s recommended aisles or zones. By the time the stower has mounted the cage on the order picker, the recommendation is already on screen.</p><p>The cage attaches directly to the back of the OP, aligned straight along the same longitudinal axis. It shares the lifting assembly with the operator platform, so the cage and platform elevate together during stowing.</p></section>
      <details class="model-details"><summary>See the real drop zone</summary><p class="impact-method">Warehouse photos from my project reference. Select a photo to view it full size.</p><div class="reference-photos"><figure><a href="assets/stowguidance/cage-lanes.jpg" target="_blank" rel="noopener noreferrer"><img src="assets/stowguidance/cage-lanes.jpg" width="1706" height="1280" loading="lazy" alt="Full mesh cages in marked work-in-progress lanes beside tall warehouse racks and yellow guardrails."></a><figcaption>Full cages in the WIP lanes.</figcaption></figure><figure><a href="assets/stowguidance/stow-drop-zone.jpg" target="_blank" rel="noopener noreferrer"><img src="assets/stowguidance/stow-drop-zone.jpg" width="1706" height="1280" loading="lazy" alt="Stow drop zone with wire cages, order pickers, yellow lane barriers, and an overhead display."></a><figcaption>The stow drop zone and OP staging.</figcaption></figure><figure><a href="assets/stowguidance/cages-and-displays.jpg" target="_blank" rel="noopener noreferrer"><img src="assets/stowguidance/cages-and-displays.jpg" width="1706" height="1280" loading="lazy" alt="Wheeled mesh cages, marked lanes, and an overhead TV in the warehouse stow area."></a><figcaption>Cages, lane separation, and overhead displays.</figcaption></figure></div></details>
      <div class="flow-demo"><div class="flow-demo-heading"><span>THE REDESIGNED CHANGEOVER</span><button type="button" id="flow-next">Start walkthrough ▶</button></div><div class="flow-steps"><div class="flow-step" data-flow-step="0"><span class="flow-number">01</span><strong>Pull through</strong><p>The cage leaves the queue through the fixed strut frame.</p></div><div class="flow-step" data-flow-step="1"><span class="flow-number">02</span><strong>Scan in motion</strong><p>The Zebra scanner reads the cage barcode automatically.</p></div><div class="flow-step" data-flow-step="2"><span class="flow-number">03</span><strong>Mount and go</strong><p>The overhead TV shows the recommended aisles by the time mounting is complete.</p></div></div><p class="flow-status" id="flow-status" role="status" aria-live="polite">The scanning and system response happen during movement and cage mounting.</p></div>
      <section class="story-section"><h3>Remove the extra waiting</h3><p>The time to scan and receive a system recommendation overlaps with movement and cage mounting. Based on my reported before-and-after timing, the design recovers approximately one minute of separate scanning and waiting per changeover.</p><p>With <strong>20 stowers</strong> changing <strong>3 cages per hour</strong>, that is <strong>60 minutes of team labor recovered for each operating hour</strong>, or 5% of the team’s time at that cage rate. At least one other building adopted the design.</p></section>
      <section class="impact-calculator" aria-labelledby="impact-title"><p class="eyebrow">MODEL THE BUILDING'S LABOR CAPACITY</p><h3 id="impact-title">What does one minute add up to?</h3><p class="impact-formula">20 stowers × 3 cages/hour × 1 minute ÷ 60 = <strong>1 labor-hour per operating hour</strong></p><p class="calculator-intro">Adjust the assumed schedule and hourly labor value. Active hours exclude breaks and other periods outside this stow workflow.</p>
      <form id="impact-form" class="impact-form"><label>Active hours per shift<input name="activeHoursPerShift" type="number" min="0" max="24" step="0.5" value="10" required inputmode="decimal"></label><label>Shifts per day<select name="shiftsPerDay"><option value="1">1 shift</option><option value="2" selected>2 shifts</option><option value="3">3 shifts</option></select></label><label>Operating days per week<input name="daysPerWeek" type="number" min="1" max="7" step="1" value="7" required inputmode="numeric"></label><label>Hourly labor value (USD)<input name="hourlyValue" type="number" min="0" max="200" step="0.01" value="30" required inputmode="decimal"></label></form>
      <p class="impact-error" id="impact-error" role="status" hidden></p><table class="impact-table"><caption class="visually-hidden">Estimated labor capacity and equivalent value under the selected schedule</caption><thead><tr><th scope="col">Period</th><th scope="col">Hours recovered</th><th scope="col">Equivalent value</th></tr></thead><tbody><tr><th scope="row">Daily</th><td id="impact-daily-hours">20 h</td><td id="impact-daily-value">$600</td></tr><tr><th scope="row">Weekly</th><td id="impact-weekly-hours">140 h</td><td id="impact-weekly-value">$4,200</td></tr><tr class="annual-row"><th scope="row">Annual</th><td id="impact-annual-hours">7,280 h</td><td id="impact-annual-value">$218,400</td></tr></tbody></table><p class="impact-summary" id="impact-summary" aria-live="polite" aria-atomic="true">Illustrative annual capacity: 7,280 labor-hours, valued at $218,400.</p>
      <p class="impact-method">Uses 52 operating weeks per year and assumes the stated staffing, cage rate, and time recovery hold throughout the selected active hours. The default schedule is an illustration, not a confirmed historical schedule.</p><p class="impact-method">The $30/hour value is a rounded compensation benchmark. Amazon reports average U.S. fulfillment and transportation pay above $23/hour and total compensation above $30/hour including benefits. It is not the building’s verified fully loaded labor rate. <a href="https://www.aboutamazon.com/news/workplace/amazon-wage-increase-2025-fulfillment-transportation-employees" target="_blank" rel="noopener noreferrer">Amazon compensation announcement, September 2025 ↗</a></p><p class="impact-method">This values recovered labor capacity at the selected rate, before installation and maintenance costs. Realized payroll savings depend on paid hours or overtime actually avoided. Current compensation benchmarks do not establish the historical dollar savings.</p></section>`,
  },
  portal: {
    number: '03', title: 'Onboarding Portal', place: "MANAGER'S DESK", color: 'var(--blue)',
    summary: 'Organization health. Team pace. Verified learning.',
    lead: 'I built the Onboarding Portal end to end to make organizational learning health visible: how teams are progressing, who is on pace, and where Senior Operations, GMs, and regional directors need to follow up.',
    tags: ['Organization-wide learning health', 'Team progress and compliance', 'End-to-end ownership'],
    content: `<button class="outline-button" type="button" data-replay-portal>View the tool screenshots ↗</button>
      <div class="impact-facts onboarding-facts" aria-label="Onboarding Portal scope"><div><strong>Org → team → person</strong><span>Learning health across the organization</span></div><div><strong>Site → region</strong><span>Visibility for Senior Operations, GMs, and regional directors</span></div><div><strong>Built by me</strong><span>Business need, design, development, and delivery</span></div></div>
      <section class="story-section"><h3>The business need</h3><p>Senior leaders needed a consistent picture of organizational learning health: which teams were progressing, who was on pace, and where support was needed before launch. Unstructured roadmaps, unclear shadowing expectations, and fragmented learning records made readiness difficult to assess.</p><p>I connected the manager learning experience to an organization-level review process, so leaders could use the same evidence to recognize progress, address gaps, and hold teams accountable for development.</p></section>
      <section class="story-section" aria-labelledby="portal-leadership-title"><h3 id="portal-leadership-title">A leadership view of organizational learning health</h3><p>Senior Operations can focus coaching by team and shift. GMs can review learning health across the site. Regional directors gain a consistent view for discussing progress and launch readiness with site leaders.</p>
      <div class="portal-capabilities"><section><span class="capability-index">01 / ORGANIZATION</span><h3>See the whole team</h3><p>The admin overview connects reporting lines, roles, and learning progress. Leaders can move from the organization chart to a team or individual to understand where support is needed.</p></section><section><span class="capability-index">02 / PACE</span><h3>Know which teams are on track</h3><p>Team rollups bring assignment compliance, active engagement, and progress against the expected pace into one review. Follow-up indicators help leaders focus their attention.</p></section><section><span class="capability-index">03 / ENGAGEMENT</span><h3>Recognize active learners and strong progress</h3><p>Separate rankings cover assignments, active engagement, weekly progress, and completion. Leaders can recognize momentum and identify coaching needs using distinct learning signals.</p></section><section><span class="capability-index">04 / TRAINING</span><h3>Connect attendance with learning validation</h3><p>The training view brings sessions, eligible learners, attendance, pass rates, and repeat attempts together. Knowledge-check submissions provide the attendance record and evidence for follow-up.</p></section></div></section>
      <section class="story-section"><h3>What I owned</h3><p>I identified the business need and built the Onboarding Portal end to end myself: requirements, interface design, development, and pilot delivery. I connected the organization overview and learning analytics to each manager’s roadmap, assignments, training records, knowledge checks, and skill-readiness assessment.</p><p>The design gives leadership a repeatable way to review development across teams, supported by a detailed learning experience for each manager. I used AI assistance in development and owned the complete solution.</p><p class="impact-method">The current pilot consolidates progress through shared team-folder records. Admin reports reflect the records loaded and synced at the time of review. Broader network hosting and corporate sign-in remain proposed next steps.</p></section>
      <details class="readiness-scenario portal-learning-details"><summary>Explore the individual manager learning experience</summary>
      <section class="roadmap-section" aria-labelledby="roadmap-title"><p class="eyebrow">REGIONAL GUIDANCE, MADE ACTIONABLE</p><h3 id="roadmap-title">One connected six-week journey</h3><ol class="week-rail" aria-label="The roadmap covers all six weeks"><li><span>WEEK</span><strong>01</strong></li><li><span>WEEK</span><strong>02</strong></li><li><span>WEEK</span><strong>03</strong></li><li><span>WEEK</span><strong>04</strong></li><li><span>WEEK</span><strong>05</strong></li><li><span>WEEK</span><strong>06</strong></li></ol><p>Each week connects its learning goals with the assigned training, practical experience, and evidence leaders need to review progress.</p></section>
      <div class="portal-capabilities"><section><span class="capability-index">01 / DIRECTION</span><h3>Weekly learning goals</h3><p>A week-by-week roadmap from regional guidance, including assigned programs from the company learning platform.</p></section><section><span class="capability-index">02 / PLANNING</span><h3>Daily and weekly calendars</h3><p>Visibility into in-person training and shadowing, so managers and leaders can see the learning schedule.</p></section><section><span class="capability-index">03 / APPLICATION</span><h3>Observations and reflections</h3><p>Weekly assignments capture what managers observe and learn, with records senior leaders can track and review.</p></section><section><span class="capability-index">04 / EVIDENCE</span><h3>Materials and attendance</h3><p>Stored in-person training materials and session records support attendance tracking and follow-up.</p></section><section><span class="capability-index">05 / VALIDATION</span><h3>Knowledge checks</h3><p>Learning checks, including checks after in-person sessions, help validate understanding and surface gaps.</p></section><section><span class="capability-index">06 / READINESS</span><h3>A skill-readiness grading matrix</h3><p>Assessment of technical skills and leadership development gives reviewers a consistent basis for readiness decisions.</p></section></div>
      </details>
      <section class="story-section"><h3>Build the business case around observable costs</h3><p>A weak onboarding process consumes time in several places: managers searching for direction, trainers and leaders coordinating or reconstructing progress, and both sides repeating instruction after missed or unvalidated learning.</p><p>The model below values reductions in that avoidable work. Delayed readiness is modeled separately. The figures are planning assumptions until before-and-after data are available.</p></section>
      <section class="onboarding-calculator impact-calculator" aria-labelledby="onboarding-impact-title">
        <p class="eyebrow">HYPOTHETICAL REGIONAL MODEL · EDITABLE ASSUMPTIONS</p>
        <h3 id="onboarding-impact-title">From one manager to a regional rollout</h3>
        <p class="calculator-intro">A hypothetical scenario: 50 new sites over two years, with about 40 managers per site, or 2,000 potential onboarding participants. The model assumes each participating manager uses the six-week program once.</p>
        <p class="impact-method">The site count is a modeling input, not a company plan. Time reductions and hourly costs below are illustrative assumptions, not measured results or verified Amazon labor rates. Required teaching and the full six-week program remain intact.</p>
        <form id="onboarding-form">
          <h4 class="model-subheading">Time and hourly cost assumptions</h4>
          <div class="impact-form">
            <label>New manager cost per hour (USD)<input name="managerHourlyCost" type="number" min="0" max="500" step="0.01" value="60" required inputmode="decimal"></label>
            <label>Trainer / reviewer cost per hour (USD)<input name="reviewerHourlyCost" type="number" min="0" max="500" step="0.01" value="90" required inputmode="decimal"></label>
            <label>New manager coordination hours recovered / week<input name="managerHoursRecoveredPerWeek" type="number" min="0" max="40" step="0.5" value="2" required inputmode="decimal"></label>
            <label>Trainer / reviewer coordination hours recovered / week<input name="reviewerHoursRecoveredPerWeek" type="number" min="0" max="40" step="0.5" value="1" required inputmode="decimal"></label>
            <label>Repeat-training hours avoided / manager<input name="jointRetrainingHoursAvoided" type="number" min="0" max="240" step="0.5" value="4" required inputmode="decimal"></label>
          </div>
          <p class="impact-method">A repeat-training hour includes one new manager and one trainer, so it represents two labor-hours. Coordination time excludes these repeat sessions and necessary teaching.</p>
          <p class="impact-error" id="onboarding-error" role="status" hidden></p>
          <table class="impact-table onboarding-table"><caption>Potential direct time recovery per manager</caption><thead><tr><th scope="col">Source</th><th scope="col">Labor-hours</th><th scope="col">Equivalent value</th></tr></thead><tbody>
            <tr><th scope="row">New manager coordination</th><td id="onboarding-manager-hours">12 h</td><td id="onboarding-manager-value">$720</td></tr>
            <tr><th scope="row">Trainer / reviewer coordination</th><td id="onboarding-reviewer-hours">6 h</td><td id="onboarding-reviewer-value">$540</td></tr>
            <tr><th scope="row">Repeated instruction</th><td id="onboarding-repeat-hours">8 h</td><td id="onboarding-repeat-value">$600</td></tr>
            <tr class="annual-row"><th scope="row">Per manager</th><td id="onboarding-total-hours">26 h</td><td id="onboarding-total-value">$1,860</td></tr>
          </tbody></table>
          <section class="regional-rollout" aria-labelledby="regional-title">
            <h4 id="regional-title" class="model-subheading">Scale the launch cohort</h4>
            <div class="impact-form">
              <label>Additional launch sites<input name="launchSites" type="number" min="0" max="10000" step="1" value="50" required inputmode="numeric"></label>
              <label>Managers per launch site<input name="managersPerSite" type="number" min="0" max="10000" step="1" value="40" required inputmode="numeric"></label>
              <label>Rollout period (years)<input name="rolloutYears" type="number" min="1" max="10" step="1" value="2" required inputmode="numeric"></label>
              <label>Managers completing portal onboarding (%)<input name="participationPercent" type="number" min="0" max="100" step="1" value="100" required inputmode="numeric"></label>
            </div>
            <p class="impact-method" id="regional-population">50 additional sites × 40 managers/site = 2,000 managers. At 100% participation: 2,000 managers onboarded once over 2 years.</p>
            <table class="impact-table onboarding-table"><caption>Projected gross labor capacity from launch onboarding</caption><thead><tr><th scope="col">Scope</th><th scope="col">Labor-hours</th><th scope="col">Equivalent value</th></tr></thead><tbody>
              <tr><th scope="row">Per launch site</th><td id="regional-site-hours">1,040 h</td><td id="regional-site-value">$74,400</td></tr>
              <tr><th scope="row">Average per rollout year</th><td id="regional-annual-hours">26,000 h</td><td id="regional-annual-value">$1,860,000</td></tr>
              <tr class="annual-row"><th scope="row" id="regional-total-label">2-year rollout total</th><td id="regional-total-hours">52,000 h</td><td id="regional-total-value">$3,720,000</td></tr>
            </tbody></table>
            <p class="impact-summary" id="regional-summary" aria-live="polite" aria-atomic="true">Projected rollout capacity: 52,000 labor-hours, valued at $3,720,000 over 2 years.</p>
            <p class="impact-method" id="regional-sensitivity">If only half the modeled time reduction is achieved at the selected participation level: 26,000 hours, valued at $1,860,000 across the rollout.</p>
            <p class="impact-method">The annual average assumes launches and onboarding are spread evenly across the rollout. This is a one-time benefit for each participating manager, not a recurring annual saving after launch. Existing sites and future replacement hires are excluded. Reduce participation if some managers do not require the full onboarding program.</p>
          </section>
          <details class="readiness-scenario"><summary>Compare a separate annual onboarding cohort</summary>
            <p class="impact-method">Use this for an ongoing onboarding population. This comparison is separate from the launch projection and is not added to it.</p>
            <div class="impact-form"><label>Managers onboarded per year<input name="managersPerYear" type="number" min="0" max="10000" step="1" value="24" required inputmode="numeric"></label></div>
            <p class="impact-summary" id="onboarding-summary" aria-live="polite" aria-atomic="true">For 24 managers/year: 624 labor-hours, valued at $44,640.</p>
          </details>
          <details class="readiness-scenario"><summary>Explore delayed readiness separately</summary>
            <p class="impact-method">This scenario addresses a readiness gap after the planned six weeks, using the separate annual cohort above. It values the portion of a manager’s capacity recovered by closing that gap earlier.</p>
            <div class="impact-form"><label>Post-program readiness-delay days avoided<input name="readinessDaysRecovered" type="number" min="0" max="60" step="0.5" value="5" required inputmode="decimal"></label><label>Manager capacity gap closed (%)<input name="readinessGapPercent" type="number" min="0" max="100" step="1" value="25" required inputmode="numeric"></label></div>
            <p class="impact-method">Days × 8 working hours × capacity gap × new manager hourly cost.</p>
            <p class="readiness-result" id="onboarding-readiness">Illustrative readiness value: $600 per manager; $14,400 across 24 managers.</p>
            <p class="impact-method">This is capacity-equivalent value, excluded from both the regional rollout and direct time-recovery totals. Count only time outside coordination and repeat training, and validate the change in readiness before attributing it to the portal.</p>
          </details>
        </form>
        <p class="impact-method">Hourly costs should reflect the actual AM, OM, trainer, and reviewer mix. These are gross labor-capacity values before development, rollout, training, support, and maintenance costs. Cash savings require a demonstrated reduction in paid labor, overtime, or hiring costs; recovered salaried time alone does not reduce payroll. Net savings and ROI are not established.</p>
        <p class="impact-method">Quality defects, safety outcomes, retention, and site-launch delays are excluded from the dollar estimate until a measurable connection is established.</p>
      </section>
      <section class="story-section"><h3>How I would validate the impact</h3><p>Track team pace, assignment compliance, active engagement, learning-check results, and completion together. Compare similar cohorts on leadership review time, coordination effort, repeated training, and days to readiness under the same grading criteria. Consistent assessments and reviewer calibration are needed to validate skill development and any improvement attributed to the portal.</p></section>`,
  },
  beams: A_LEVEL_BEAMS,
  ai: AI_PROJECT,
};
export const ADDITIONAL_WORK = {
  quality: {
    title: 'Build quality into the operation.', label: 'QUALITY & LAUNCH READINESS',
    lead: 'A risk-based framework for making quality ownership and daily execution part of a new operation.',
    content: `<div class="project-tags"><span>Quality framework design</span><span>Launch planning</span></div><section class="story-section"><h3>Recognize the risk early</h3><p>I organized the framework around operational risks, including inventory dwell, work-in-progress accumulation, inconsistent follow-through, and knowledge gaps. Each risk connects to concrete controls and ownership.</p></section><section class="story-section"><h3>Make the response clear</h3><ul><li><strong>Early visibility:</strong> use inventory age and dwell as signals for action.</li><li><strong>Recovery ownership:</strong> define the owner, checkpoint, and escalation path.</li><li><strong>Recurring execution:</strong> connect audits, reviews, handoffs, and manager deliverables.</li><li><strong>Knowledge reinforcement:</strong> use role qualification and targeted refresher checks.</li></ul></section><section class="story-section"><h3>The intended outcome</h3><p>A quality system that managers can execute consistently, with clearer accountability and earlier intervention. This work is presented as launch planning; operating outcomes depend on implementation and follow-through.</p></section>`,
  },
  inventory: {
    title: 'Make accuracy part of daily work.', label: 'INVENTORY & OPERATING DISCIPLINE',
    lead: 'My operating focus in Inventory Control and Quality Assurance.',
    content: `<section class="story-section"><h3>Connect the count to the cause</h3><p>Inventory counts identify discrepancies. Defect research connects those discrepancies to the process and behavior that created them, so the next action addresses the underlying issue.</p></section><section class="story-section"><h3>Connect quality to operations</h3><p>My experience across receiving, stowing, and ICQA gives me a view of how decisions in one process affect the next. I focus on ownership, standard work, and practical follow-through between teams.</p></section><section class="story-section"><h3>Make the work repeatable</h3><p>Audits, quality reviews, coaching, and knowledge reinforcement all have a role. The leadership task is to connect them into an operating rhythm that supports consistent execution.</p></section><section class="story-section"><h3>Develop the people behind the process</h3><p>I joined Amazon as an L4 Area Manager through college hiring and progressed into operations and ICQA leadership. I focus on clear expectations, team development, and practical improvements grounded in the work.</p></section>`,
  },
};
